version: '3'
services:
  app:
    container_name: wordyApp
    build: ./app
    links:
      - db
    ports:
      - "8888:8888"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypwd
    volumes:
      - ./octopus/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    
